seed: 0
device: cuda:0
path:
  base_dir: experiments/{dataset}/{mode}/{model}
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: experiments/{dataset}/{mode}/{model}/checkpoint/best_model.pth

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  type: AdamW
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: &n_epoch 30
    power: 2.0

run:
  n_epoch: *n_epoch
  val_per_epoch: 5
  log_per_iter: 16