seed: 2506
device: cuda:0
path:
  name: custom
  base_dir: experiments/linear_static/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: experiments/linear_static/single/checkpoint/best_model.pth
dataset:
  common_base: &common_base
    max_frame_corr: 2
    filter_params: null
    pcd_sample_num: -1
  common_main: &common_main
    max_deg: 15
    max_tran: 0.1
    mag_randomly: true
  args:
    - name: seq_00
      base:
        gt_Tcl: data/colmap/00/gt.txt
        image_dir: data/colmap/00/images_col
        lidar_dir: data/colmap/00/lidar
        lidar_pose: data/colmap/00/lidar_pg.json
        model_dir: data/colmap/00/sparse_col/0/
        pair_file: data/colmap/00/seq_pair.json
        kpt_dir: data/colmap/00/disk/keypoint
        match_dir: data/colmap/00/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/00.txt
    - name: seq_02
      base:
        gt_Tcl: data/colmap/02/gt.txt
        image_dir: data/colmap/02/images_col
        lidar_dir: data/colmap/02/lidar
        lidar_pose: data/colmap/02/lidar_pg.json
        model_dir: data/colmap/02/sparse_col/0/
        pair_file: data/colmap/02/seq_pair.json
        kpt_dir: data/colmap/02/disk/keypoint
        match_dir: data/colmap/02/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/02.txt
    - name: seq_05
      base:
        gt_Tcl: data/colmap/05/gt.txt
        image_dir: data/colmap/05/images_col
        lidar_dir: data/colmap/05/lidar
        lidar_pose: data/colmap/05/lidar_pg.json
        model_dir: data/colmap/05/sparse_col/0/
        pair_file: data/colmap/05/seq_pair.json
        kpt_dir: data/colmap/05/disk/keypoint
        match_dir: data/colmap/05/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/05.txt
    - name: seq_06
      base:
        gt_Tcl: data/colmap/06/gt.txt
        image_dir: data/colmap/06/images_col
        lidar_dir: data/colmap/06/lidar
        lidar_pose: data/colmap/06/lidar_pg.json
        model_dir: data/colmap/06/sparse_col/0/
        pair_file: data/colmap/06/seq_pair.json
        kpt_dir: data/colmap/06/disk/keypoint
        match_dir: data/colmap/06/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/06.txt
model:
  surrogate:
    hidden_dims: [128, 128, 128, 128]
    x_dim: 6
    encoder_argv:
      resnet_depth: 18
      resnet_pretrained: pretrained/resnet18-5c106cde.pth
      encoder_2d_chans: [64, 96, 128, 192]
      encoder_3d_chans: [64, 96, 128, 192]
      pcd_pyramid: [2048, 1024, 512]
  diffuser:
    beta_schedule:
      schedule: linear
      n_timestep: 1000
      linear_start: 1.0E-4
      linear_end: 0.02
    sampling_argv:
      steps: 10
      order: 3
      skip_type: logSNR
      method: multistep
      lower_order_final: false
      denoise_to_zero: false
      solver_type: dpmsolver
      atol: 0.005
      rtol: 0.05
  guidance:
    argv:
      loss_fn:
        type: mae
        args:
          reduction: mean
      cba_argv:
        max_dist: 2.0
        proj_constraint: true
      ca_argv:
        max_dist: 0.5
        normal_radius: 1.0
        noraml_knn: 30
        ca_knn: 10
        norm_reg_err: 0.04
    grad_place_holder: null
    t_threshold: 0.3
    scale: 1.0E-3

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 5.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: step
  args:
    step_size: 5
    gamma: 0.5
run:
  n_epoch: 50
  val_per_epoch: 5
  log_per_iter: 16

