seed: 2514
device: cuda:0
path:
  name: custom
  base_dir: experiments/linear_static/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: experiments/linear_static/single/checkpoint/best_model.pth
dataset:
  common_base: &common_base
    max_frame_corr: 2
    resize_size: null
    filter_params:
      voxel_size: 0.15
      min_dist: 0.15
    pcd_sample_num: -1
  common_main: &common_main
    max_deg: 15
    max_tran: 0.1
    mag_randomly: true
  args:
    - name: seq_13
      base:
        gt_Tcl: data/colmap/13/gt.txt
        image_dir: data/colmap/13/images_col
        lidar_dir: data/colmap/13/lidar
        lidar_pose: data/colmap/13/lidar_pg.json
        camera_db: data/colmap/13/sparse_col/0/cameras.bin
        image_db: data/colmap/13/sparse_col/0/images.bin
        pair_file: data/colmap/13/seq_pair.json
        kpt_dir: data/colmap/13/disk/keypoint
        match_dir: data/colmap/13/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/13.txt
    - name: seq_14
      base:
        gt_Tcl: data/colmap/14/gt.txt
        image_dir: data/colmap/14/images_col
        lidar_dir: data/colmap/14/lidar
        lidar_pose: data/colmap/14/lidar_pg.json
        camera_db: data/colmap/14/sparse_col/0/cameras.bin
        image_db: data/colmap/14/sparse_col/0/images.bin
        pair_file: data/colmap/14/seq_pair.json
        kpt_dir: data/colmap/14/disk/keypoint
        match_dir: data/colmap/14/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/14.txt
    - name: seq_15
      base:
        gt_Tcl: data/colmap/15/gt.txt
        image_dir: data/colmap/15/images_col
        lidar_dir: data/colmap/15/lidar
        lidar_pose: data/colmap/15/lidar_pg.json
        camera_db: data/colmap/15/sparse_col/0/cameras.bin
        image_db: data/colmap/15/sparse_col/0/images.bin
        pair_file: data/colmap/15/seq_pair.json
        kpt_dir: data/colmap/15/disk/keypoint
        match_dir: data/colmap/15/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/15.txt
    - name: seq_21
      base:
        gt_Tcl: data/colmap/21/gt.txt
        image_dir: data/colmap/21/images_col
        lidar_dir: data/colmap/21/lidar
        lidar_pose: data/colmap/21/lidar_pg.json
        camera_db: data/colmap/21/sparse_col/0/cameras.bin
        image_db: data/colmap/21/sparse_col/0/images.bin
        pair_file: data/colmap/21/seq_pair.json
        kpt_dir: data/colmap/21/disk/keypoint
        match_dir: data/colmap/21/disk/match
        <<: *common_base
      main:
        <<: *common_main
        file: cache/custom/21.txt
model:
  surrogate:
    hidden_dims: [128, 128, 128, 128]
    x_dim: 6
    encoder_argv:
      resnet_depth: 18
      resnet_pretrained: pretrained/resnet18-5c106cde.pth
      encoder_2d_chans: [64, 96, 128, 192]
      encoder_3d_chans: [64, 96, 128, 192]
      pcd_pyramid: [2048, 1024, 512]
  diffuser:
    beta_schedule:
      schedule: linear
      n_timestep: 1000
      linear_start: 1.0E-4
      linear_end: 0.02
    dpm_argv:
      steps: 10
      order: 3
      skip_type: logSNR
      method: multistep
      lower_order_final: false
      denoise_to_zero: false
      solver_type: dpmsolver
      atol: 0.005
      rtol: 0.05
  guidance:
    argv:
      loss_fn:
        type: mae
        args:
          reduction: mean
      max_corr_dist: 1.5
      proj_constraint: true
    t_threshold: 0.5
    scale: 1.0E-3

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 5.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: step
  args:
    step_size: 5
    gamma: 0.5
run:
  n_epoch: 50
  val_per_epoch: 5
  log_per_iter: 16

