seed: 2514
device: cuda:0
path:
  name: single
  base_dir: experiments/linear_static/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: experiments/linear_static/single/checkpoint/best_model.pth
dataset:
  common_args: &dataset_common_args
    basedir: ./data/kitti/
    cam_id: 2
    meta_json: 'data_len.json'
    skip_frame: 1
    voxel_size: 0.15
    pcd_sample_num: 4096
    resize_size: null
    extend_ratio: [2.5, 2.5]
  train:
    dataset:
      train:
        base:
          seqs: ['00','01','02','03','04','07','08']
          <<: *dataset_common_args
        main: &train_main
          max_deg: 15
          max_tran: 0.1
          mag_randomly: false
      val:
        base:
          seqs: ['05','06']
          <<: *dataset_common_args
        main:
          max_deg: 15
          max_tran: 0.1
          mag_randomly: true
    dataloader:
      common_args: &dataloader_common_args
        num_workers: 6
        pin_memory: true
      args:
        batch_sampler:
          dataset_len: 128
          num_samples: 8
        <<: *dataloader_common_args
      val_args:
        batch_sampler:
          dataset_len: 128
          num_samples: 8
        <<: *dataloader_common_args
  test:
    common_main: &test_common_main
      max_deg: 15
      max_tran: 0.1
      mag_randomly: false
    dataset:
      - name: seq_13
        base:
          seqs: ['13']
          <<: *dataset_common_args
        main:
          <<: *test_common_main
          file: cache/test_13.txt
      - name: seq_14
        base:
          seqs: ['14']
          <<: *dataset_common_args
        main:
          <<: *test_common_main
          file: cache/test_14.txt
      - name: seq_15
        base:
          seqs: ['15']
          <<: *dataset_common_args
        main:
          <<: *test_common_main
          file: cache/test_15.txt

    dataloader:
      batch_size: 32
      shuffle: false
      drop_last: false
      pin_memory: true
      num_workers: 8
model:
  surrogate:
    hidden_dims: [128, 128, 128, 128]
    x_dim: 6
    encoder_argv:
      resnet_depth: 18
      resnet_pretrained: pretrained/resnet18-5c106cde.pth
      encoder_2d_chans: [64, 96, 128, 192]
      encoder_3d_chans: [64, 96, 128, 192]
      pcd_pyramid: [2048, 1024, 512]
  diffuser:
    beta_schedule:
      schedule: linear
      n_timestep: 1000
      linear_start: 1.0E-4
      linear_end: 0.02
    dpm_argv:
      steps: 10
      order: 3
      skip_type: logSNR
      method: multistep
      lower_order_final: false
      denoise_to_zero: false
      solver_type: dpmsolver
      atol: 0.005
      rtol: 0.05

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 5.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: step
  args:
    step_size: 5
    gamma: 0.5
run:
  n_epoch: 50
  val_per_epoch: 5
  log_per_iter: 16

