seed: 0
device: cuda:0
path:
  name: calibnet
  base_dir: experiments/resize/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/resize/calibnet/checkpoint/best_model.pth
dataset:
  common_args: &dataset_common_args
    basedir: ./data/kitti/
    cam_id: 2
    meta_json: 'data_len.json'
    skip_frame: 1
    voxel_size: null
    resize_size: &img_size [256, 512]
    extend_ratio: [2.5, 2.5]
  train_val_args: &train_val_dataset_args
    <<: *dataset_common_args
    min_dist: 0.1
    skip_point: 1
    pcd_sample_num: 40000
  test_args: &test_dataset_args
    <<: *dataset_common_args
    min_dist: 0.1
    skip_point: 1
    pcd_sample_num: 40000
  train:
    dataset:
      train:
        base:
          seqs: ['00','02','03','04','05','06','07','08','10','12']
          <<: *train_val_dataset_args
        main: &train_main
          max_deg: 15
          max_tran: 0.1
          mag_randomly: false
      val:
        base:
          seqs: ['16','17','18']
          <<: *train_val_dataset_args
        main:
          max_deg: 15
          max_tran: 0.1
          mag_randomly: true
    dataloader:
      common_args: &dataloader_common_args
        num_workers: 8
        pin_memory: true
      args:
        batch_sampler:
          dataset_len: 512
          num_samples: 8
        <<: *dataloader_common_args
      val_args:
        batch_sampler:
          dataset_len: 256
          num_samples: 8
        <<: *dataloader_common_args
  test:
    common_main: &test_common_main
      max_deg: 15
      max_tran: 0.1
      mag_randomly: true
    dataset:
      - name: seq_13
        base:
          seqs: ['13']
          <<: *test_dataset_args
        main:
          <<: *test_common_main
          file: cache/kitti/test_13.txt
      - name: seq_14
        base:
          seqs: ['14']
          <<: *test_dataset_args
        main:
          <<: *test_common_main
          file: cache/kitti/test_14.txt
      - name: seq_15
        base:
          seqs: ['15']
          <<: *test_dataset_args
        main:
          <<: *test_common_main
          file: cache/kitti/test_15.txt
      - name: seq_20
        base:
          seqs: ['20']
          <<: *test_dataset_args
        main:
          <<: *test_common_main
          file: cache/kitti/test_20.txt
      - name: seq_21
        base:
          seqs: ['21']
          <<: *test_dataset_args
        main:
          <<: *test_common_main
          file: cache/kitti/test_21.txt

    dataloader:
      batch_size: 16
      shuffle: false
      drop_last: false
      pin_memory: true
      num_workers: 8
model:
  surrogate:
    type: CalibNet
    argv:
      calibnet_argv:
        res_num: 18
        depth_resnet_argv:
          inplanes: 1
          planes: 32
        aggregation_argv:
          planes: 96
          final_feat: [2,4]
      pcd2depth_argv:
        pooling_size: 3
        max_depth: 50.0
  diffuser:
    beta_schedule:
      schedule: cosine
      n_timestep: 1000
      linear_start: 1.0E-4
      linear_end: 0.02
    dpm_argv:
      steps: 10
      order: 3
      skip_type: logSNR
      method: multistep
      lower_order_final: false
      denoise_to_zero: false
      solver_type: dpmsolver
      atol: 0.005
      rtol: 0.05
  # guidance:
  #   argv:
  #     loss_fn:
  #       type: mae
  #       args:
  #         reduction: mean
  #     max_corr_dist: 1.5
  #     proj_constraint: true
  #   t_threshold: 0.5

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 2.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: step
  args:
    step_size: 5
    gamma: 0.5
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16
