# ProjFusion implemented with SE(3) Diffusion
seed: 0
device: cuda:0
path:
  name: main
  base_dir: experiments/large/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/large/main/checkpoint/best_model.pth
  
model:
  surrogate:
    type: ProjFusionNet  # Chosen from ['ProjFusionNet','LCCNet','CalibNet','RGGNet','LCCRAFT'], argv should match relative class as well
    argv:
      activation: leakyrelu
      inplace: true
      encoder_argv:
        resnet_depth: 18
        resnet_pretrained: true
        encoder_3d_chans: [32, 64, 128, 256]
        pcd_pyramid: [4096, 2048, 1024, 512]
        max_depth: 50.0
        proj_planes: 32
        encoder_3d_knn: 16
        fusion_knn: 4
        union_feat_size: [8, 16]
      aggregation_argv:
        planes: 128
        final_feat: [2, 4]
        rot_mlp_dims: [512, 256]
        tsl_mlp_dims: [512, 256]
      proj_features: true
      depth_features: true
      
  diffusion_scheduler:
    train:
      schedule_type: cosine
      n_diff_steps: 200
      beta_1: 1.0E-4
      beta_T: 0.05
      sigma_r: 0.05
      sigma_t: 0.03
      add_noise: true
    val:
      schedule_type: cosine
      n_diff_steps: 10
      beta_1: 0.2
      beta_T: 0.8
      sigma_r: 0.1
      sigma_t: 0.01
      add_noise: true
loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16