name: nuscenes
dataset:
  type: nuscenes
  common_args: &dataset_common_args
    dataroot: data/nuscenes/v1.0-full
    daylight: false
    cam_sensor_name: CAM_FRONT # choose from ['CAM_FRONT','CAM_FRONT_RIGHT','CAM_BACK_RIGHT','CAM_BACK','CAM_BACK_LEFT','CAM_FRONT_LEFT']
    point_sensor_name: LIDAR_TOP
    skip_point: 1
    voxel_size: null
    min_dist: 0.1
    pcd_sample_num: 8192
    resize_size: [224, 448]
    extend_ratio: [2.5, 2.5]
  
  train:
    dataset:
      train:
        base:
          version: v1.0-trainval
          scene_names: data/nuscenes/split/train.txt
          <<: *dataset_common_args
        main: &train_main
          max_deg: &max_deg 15
          max_tran: &max_tran 0.15
          mag_randomly: false
      val:
        base:
          version: v1.0-trainval
          scene_names: data/nuscenes/split/val.txt
          <<: *dataset_common_args
        main:
          max_deg: *max_deg
          max_tran: *max_tran
          mag_randomly: true
    dataloader:
      common_args: &dataloader_common_args
        num_workers: 8
        pin_memory: true
      args:
        batch_sampler:
          dataset_len: 512
          num_samples: 16
        <<: *dataloader_common_args
      val_args:
        batch_sampler:
          dataset_len: 256
          num_samples: 16
        <<: *dataloader_common_args
  test:
    common_main: &test_common_main
      max_deg: *max_deg
      max_tran: *max_tran
      mag_randomly: true
    dataset:
      name: nuscenes
      base:
        version: v1.0-test
        scene_names: null
        <<: *dataset_common_args
      main:
        <<: *test_common_main
        

    dataloader:
      batch_size: 16
      shuffle: false
      drop_last: false
      pin_memory: true
      num_workers: 8

