seed: 0
device: cuda:0
path:
  name: lccnet
  base_dir: experiments/resize/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/resize/lccnet/checkpoint/best_model.pth
  
model:
  surrogate:
    type: LCCNet
    argv:
      lccnet_argv:
        image_size: [256, 512]
        use_feat_from: 1
        md: 4
        use_reflectance: false
        dropout: 0.0
        Action_Func: leakyrelu
        attention: false
        res_num: 18
      pcd2depth_argv:
        pooling_size: 5
        max_depth: 50.0
  diffuser:
    beta_schedule:
      schedule: cosine
      n_timestep: 1000
      linear_start: 1.0E-4
      linear_end: 0.02
    dpm_argv:
      steps: 10
      order: 3
      skip_type: logSNR
      method: multistep
      lower_order_final: false
      denoise_to_zero: false
      solver_type: dpmsolver
      atol: 0.005
      rtol: 0.05

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16