seed: 0
device: cuda:0
path:
  name: main
  base_dir: experiments/resize/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/resize/main/checkpoint/best_model.pth
  
model:
  surrogate:
    type: ProjFusionNet  # Chosen from ['ProjFusionNet','LCCNet','CalibNet'], argv should match relative class as well
    argv:
      activation: leakyrelu
      inplace: true
      encoder_argv:
        resnet_depth: 18
        resnet_pretrained: true
        encoder_2d_chans: [256]
        encoder_3d_chans: [32, 64, 128, 256]
        pcd_pyramid: [4096, 2048, 1024, 512]
        max_depth: 50.0
        proj_planes: 32
        encoder_3d_knn: 16
        fusion_knn: 4
        union_feat_size: [8, 16]
      aggregation_argv:
        planes: 96
        final_feat: [2, 4]
        mlp_dims: [256, 128]

  diffuser:
    beta_schedule:
      schedule: cosine
      n_timestep: 1000
      linear_start: 1.0E-4
      linear_end: 0.02
    dpm_argv:
      steps: 10
      order: 3
      skip_type: logSNR
      method: multistep
      lower_order_final: false
      denoise_to_zero: false
      solver_type: dpmsolver
      atol: 0.005
      rtol: 0.05
loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16