seed: 0
device: cuda:0
path:
  name: lccraft_large
  base_dir: experiments/kitti/nlsd/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/kitti/nlsd/lccraft_large/checkpoint/best_model.pth

model:
  surrogate:
    type: LCCRAFT
    argv:
      lccraft_argv:
        feature_encoder_layers: [64, 64, 128, 192, 256]
        feature_encoder_block: residualblock
        feature_encoder_norm_layer: batchnorm
        context_encoder_layers: [64, 64, 128, 192, 256]
        context_encoder_block: residualblock
        context_encoder_norm_layer: null
        corr_block_num_levels: 4
        corr_block_radius: 3
        motion_encoder_corr_layers: [96]
        motion_encoder_flow_layers: [64, 32]
        motion_encoder_out_channels: 82
        recurrent_block_hidden_state_size: 96
        recurrent_block_kernel_size: [3,3]
        recurrent_block_padding: [1,1]
        flow_head_hidden_size: 128
        depth_gen_pooling_size: 1
        depth_gen_max_depth: 50.0
        feat_poooling_size: [2,4]
        fps_num: 1024
      num_iters: 5
  diffusion_scheduler:
    train:
      schedule_type: cosine
      n_diff_steps: 200
      beta_1: 1.0E-4
      beta_T: 0.05
      sigma_r: 0.05
      sigma_t: 0.03
      add_noise: true
    val:
      schedule_type: cosine
      n_diff_steps: 10
      beta_1: 0.2
      beta_T: 0.8
      sigma_r: 0.1
      sigma_t: 0.01
      add_noise: true

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  type: AdamW
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16