seed: 0
device: cuda:0
path:
  name: rggnet
  base_dir: experiments/kitti/nlsd/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/kitti/nlsd/rggnet/checkpoint/best_model.pth
  
model:
  surrogate:
    type: RGGNet
    argv:
      rggnet_argv:
        vae_path: experiments/kitti/nlsd/vae/checkpoint/best_model.pth
        vae_argv:
          img_size: [256, 512]
          in_chan: 4
          latent_dim: 100
          hidden_dims: [64, 128, 64, 32]
          activation: leakyrelu
          inplace: true
        resnet_depth: 18
        resnet_pretrained: true
        mlp_head_dims: [512, 128]
        mlp_sub_dims: [128]
        activation: relu
        inplace: true
      pcd2depth_argv:
        pooling_size: 1
        max_depth: 50.0
      kld_weight: 1.0E-6
      ELBO_weight: 1.0E-2
  diffusion_scheduler:
    train:
      schedule_type: cosine
      n_diff_steps: 200
      beta_1: 1.0E-4
      beta_T: 0.05
      sigma_r: 0.05
      sigma_t: 0.03
      add_noise: true
    val:
      schedule_type: cosine
      n_diff_steps: 10
      beta_1: 0.2
      beta_T: 0.8
      sigma_r: 0.1
      sigma_t: 0.01
      add_noise: true

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  type: AdamW
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16