seed: 0
device: cuda:0
path:
  name: calibnet
  base_dir: experiments/multirange/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model
    - experiments/multirange/calibnet/checkpoint/best_stage_0.pth
    - experiments/multirange/calibnet/checkpoint/best_stage_1.pth
    - experiments/multirange/calibnet/checkpoint/best_stage_2.pth
  
model:
  surrogate:
    type: CalibNet
    argv:
      calibnet_argv:
        res_num: 18
        depth_resnet_argv:
          inplanes: 1
          planes: 32
        aggregation_argv:
          planes: 96
          final_feat: [2,4]
          dropout: 0.0
      pcd2depth_argv:
        pooling_size: 1
        max_depth: 50.0

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16