seed: 0
device: cuda:0
path:
  name: lccraft_small
  base_dir: experiments/multirange/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model
    - experiments/multirange/lccraft_small/checkpoint/best_stage_0.pth
    - experiments/multirange/lccraft_small/checkpoint/best_stage_1.pth
    - experiments/multirange/lccraft_small/checkpoint/best_stage_2.pth

model:
  surrogate:
    type: LCCRAFT
    argv:
      lccraft_argv:
        feature_encoder_layers: [64, 64, 128, 192, 256]
        feature_encoder_block: bottleneck
        feature_encoder_norm_layer: instancenorm
        context_encoder_layers: [64, 64, 128, 192, 256]
        context_encoder_block: bottleneck
        context_encoder_norm_layer: null
        corr_block_num_levels: 4
        corr_block_radius: 3
        motion_encoder_corr_layers: [96]
        motion_encoder_flow_layers: [64, 32]
        motion_encoder_out_channels: 82
        recurrent_block_hidden_state_size: 96
        recurrent_block_kernel_size: [3,3]
        recurrent_block_padding: [1,1]
        flow_head_hidden_size: 128
        depth_gen_pooling_size: 1
        depth_gen_max_depth: 50.0
        feat_poooling_size: [2,4]
        fps_num: 1024
      num_iters: 5

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16