seed: 0
device: cuda:0
path:
  name: rggnet
  base_dir: experiments/multirange/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model
    - experiments/multirange/rggnet/checkpoint/best_stage_0.pth
    - experiments/multirange/rggnet/checkpoint/best_stage_1.pth
    - experiments/multirange/rggnet/checkpoint/best_stage_2.pth
    - experiments/multirange/rggnet/checkpoint/best_stage_3.pth
    - experiments/multirange/rggnet/checkpoint/best_stage_4.pth
  
model:
  surrogate:
    type: RGGNet
    argv:
      rggnet_argv:
        vae_path: experiments/large/vae/checkpoint/best_model.pth
        vae_argv:
          img_size: [256, 512]
          in_chan: 4
          latent_dim: 100
          hidden_dims: [64, 128, 64, 32]
          activation: leakyrelu
          inplace: true
        resnet_depth: 18
        resnet_pretrained: true
        mlp_head_dims: [512, 128]
        mlp_sub_dims: [128]
        activation: relu
        inplace: true
      pcd2depth_argv:
        pooling_size: 1
        max_depth: 50.0
      kld_weight: 1.0E-6
      ELBO_weight: 1.0E-2

loss:
  type: mae
  args:
    reduction: mean

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 1.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16