seed: 0
device: cuda:0
path:
  name: vae
  base_dir: experiments/debug/
  log: log
  results: results
  checkpoint: checkpoint
  resume: null
  pretrain: &pretrained_model experiments/resize/vae/checkpoint/best_model.pth

vae:
  argv:
    img_size: [256, 512]
    in_chan: 4
    latent_dim: 100
    hidden_dims: [64, 128, 64, 32]
    activation: leakyrelu
    inplace: true
  kld_weight: 1.0E-6
  depthgen_argv:
    pooling_size: 1
    max_depth: 50.0

optimizer:
  args:
    lr: 1.0E-4
    betas: [0.9, 0.999]
  max_grad: 3.0

scheduler:
  type: poly
  args:
    total_iters: 30
    power: 2.0
run:
  n_epoch: 30
  val_per_epoch: 5
  log_per_iter: 16
